name: Set Stack Variables

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

    outputs:
      stack_name:
        description: "Full stack name"
        value: ${{ jobs.stack_context.outputs.stack_name }}
      ssm_namespace:
        description: "SSM namespace"
        value: ${{ jobs.stack_context.outputs.ssm_namespace }}
      stack_prefix:
        description: "Stack prefix"
        value: ${{ jobs.stack_context.outputs.stack_prefix }}

jobs:
  stack_context:
    runs-on: ubuntu-latest
    outputs:
      stack_name: ${{ steps.stack_context.outputs.stack_name }}
      ssm_namespace: ${{ steps.stack_context.outputs.ssm_namespace }}
      stack_prefix: ${{ steps.stack_context.outputs.stack_prefix }}

    steps:
      - name: Set Environment Vars
        id: stack_context
        run: |
          APP="${{ vars.SSM_ORG_NAME }}"
          REF_TYPE="${{ github.ref_type }}"

          if [[ "$REF_TYPE" == "tag" ]]; then
            ENV="prod"
          else
            ENV="dev"
          fi

          STACK_PREFIX="$APP-$ENV"
          STACK_NAME="$STACK_PREFIX-${{ inputs.service_name }}"
          SSM_NAMESPACE="/$APP/$ENV"

          echo "STACK_NAME=$STACK_NAME" >> $GITHUB_ENV
          echo "SSM_NAMESPACE=$SSM_NAMESPACE" >> $GITHUB_ENV
          echo "STACK_PREFIX=$STACK_PREFIX" >> $GITHUB_ENV

          echo "stack_name=$STACK_NAME" >> $GITHUB_OUTPUT
          echo "ssm_namespace=$SSM_NAMESPACE" >> $GITHUB_OUTPUT
          echo "stack_prefix=$STACK_PREFIX" >> $GITHUB_OUTPUT
