name: Org Deploy Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying version
        run: echo "Deploying version ${{ inputs.version }}"
